version: '3.8'

services:
  mysql-container:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - network-mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  extractor:
    build: ./extractor
    volumes:
      - data:/data
    restart: always

  processor:
    build: ./processor
    volumes:
      - data:/data
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: mydatabase
    depends_on:
      mysql-container:
        condition: service_healthy
    networks:
      - network-mysql
    restart: always

volumes:
  data:
  mysql_data:

networks:
  network-mysql:
    driver: bridge
    name: network-apoena